image: tiangolo/docker-with-compose

variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
    REGISTRY_NAME: gitlab.competa.com:5050/sea-tool/sea-tool-backend
    CONTAINER_IMAGE: $REGISTRY_NAME:$CI_BUILD_REF_SLUG

services:
    - docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY


stages:
    - build
    - test

build-dev:
    stage: build
    script:
        - cp .env.example .env
        - cp ./docker/dev/Dockerfile Dockerfile
        - docker build -t $CONTAINER_IMAGE .
        - docker push $CONTAINER_IMAGE

unit-tests:
    stage: test
    script:
        - docker pull $CONTAINER_IMAGE
        - docker run --rm -i $CONTAINER_IMAGE bash test.sh

check-project:
    stage: test
    script:
        - cp .env.example .env
        - docker run --rm -i $CONTAINER_IMAGE bash check-project.sh
