repos:
  -   repo: https://github.com/ambv/black
      rev: stable
      hooks:
      - id: black
        language_version: python3.8
        exclude: migrations
  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.9
      hooks:
      - id: flake8
        args: [--config=setup.cfg]
