version: '3'

services:
  backend: &backend
    container_name: backend_prod
    build:
      context: ./
      dockerfile: docker/prod/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - main

networks:
  main:
    driver: bridge
